-- Supabase Postgres schema for 树洞 MVP
-- 执行位置：Supabase Dashboard -> SQL Editor
-- 说明：
-- - 使用 auth.users 作为账号来源（Supabase Auth）
-- - 业务表在 public schema
-- - 为了让前端/Server Actions 无需显式写 author_user_id，使用 DEFAULT auth.uid()

-- ========== Extensions ==========
create extension if not exists pgcrypto;

-- ========== Dictionaries ==========
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  sort_order int not null default 0
);

create table if not exists public.report_reasons (
  id smallint primary key,
  label text not null,
  is_active boolean not null default true
);

-- ========== Content ==========
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_user_id uuid not null default auth.uid() references auth.users(id),
  category_id bigint not null references public.categories(id),
  title text,
  body text not null,
  status text not null default 'normal',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_posts_status check (status in ('normal','deleted','folded'))
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_user_id uuid not null default auth.uid() references auth.users(id),
  body text not null,
  status text not null default 'normal',
  created_at timestamptz not null default now(),
  constraint ck_comments_status check (status in ('normal','deleted'))
);

-- 互动：点赞/抱抱二选一（用户对同一帖子唯一）
create table if not exists public.post_reactions (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id),
  reaction_type text not null,
  created_at timestamptz not null default now(),
  constraint ck_reaction_type check (reaction_type in ('like','hug')),
  constraint uq_post_reaction unique (post_id, user_id)
);

-- 举报：可举报帖子或评论（二选一）
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_user_id uuid not null default auth.uid() references auth.users(id),
  post_id bigint references public.posts(id) on delete cascade,
  comment_id bigint references public.comments(id) on delete cascade,
  reason_id smallint not null references public.report_reasons(id),
  note text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  handled_at timestamptz,
  constraint ck_reports_status check (status in ('pending','handled')),
  constraint ck_reports_target_one check (
    (post_id is not null and comment_id is null) or
    (post_id is null and comment_id is not null)
  )
);

-- 封禁：被封禁用户禁止写入（发帖/评论/互动/举报）
create table if not exists public.user_bans (
  user_id uuid primary key references auth.users(id) on delete cascade,
  is_active boolean not null default true,
  banned_at timestamptz not null default now(),
  banned_by uuid references auth.users(id),
  note text
);

-- ========== updated_at trigger ==========
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_posts_updated_at on public.posts;
create trigger trg_posts_updated_at
before update on public.posts
for each row execute function public.set_updated_at();

-- ========== Stats views ==========
create or replace view public.post_stats as
select
  p.id as post_id,
  coalesce(c.comment_count, 0) as comment_count,
  coalesce(r.like_count, 0) as like_count,
  coalesce(r.hug_count, 0) as hug_count
from public.posts p
left join (
  select post_id, count(*)::int as comment_count
  from public.comments
  where status = 'normal'
  group by post_id
) c on c.post_id = p.id
left join (
  select
    post_id,
    count(*) filter (where reaction_type = 'like')::int as like_count,
    count(*) filter (where reaction_type = 'hug')::int as hug_count
  from public.post_reactions
  group by post_id
) r on r.post_id = p.id;

create or replace view public.post_list as
select
  p.id,
  p.title,
  p.body,
  p.created_at,
  p.category_id,
  cat.name as category_name,
  p.status,
  s.comment_count,
  s.like_count,
  s.hug_count
from public.posts p
join public.categories cat on cat.id = p.category_id
left join public.post_stats s on s.post_id = p.id;

-- ========== Seed data (optional but recommended) ==========
insert into public.categories(name, sort_order)
values ('学习', 10), ('情感', 20), ('宿舍', 30), ('其他', 40)
on conflict (name) do nothing;

insert into public.report_reasons(id, label)
values (1, '人身攻击'), (2, '隐私泄露'), (3, '色情低俗'), (4, '违法违规'), (5, '其他')
on conflict (id) do nothing;

-- ========== RLS ==========
alter table public.categories enable row level security;
alter table public.report_reasons enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.post_reactions enable row level security;
alter table public.reports enable row level security;
alter table public.user_bans enable row level security;

-- 公开可读（MVP）
drop policy if exists "categories_read" on public.categories;
create policy "categories_read" on public.categories
for select using (is_active = true);

drop policy if exists "report_reasons_read" on public.report_reasons;
create policy "report_reasons_read" on public.report_reasons
for select using (is_active = true);

drop policy if exists "posts_read" on public.posts;
create policy "posts_read" on public.posts
for select using (status = 'normal');

drop policy if exists "comments_read" on public.comments;
create policy "comments_read" on public.comments
for select using (status = 'normal');

-- 写入需登录
drop policy if exists "posts_insert" on public.posts;
create policy "posts_insert" on public.posts
for insert to authenticated
with check (
  auth.uid() = author_user_id
  and not exists (
    select 1
    from public.user_bans b
    where b.user_id = auth.uid() and b.is_active = true
  )
);

drop policy if exists "comments_insert" on public.comments;
create policy "comments_insert" on public.comments
for insert to authenticated
with check (
  auth.uid() = author_user_id
  and not exists (
    select 1
    from public.user_bans b
    where b.user_id = auth.uid() and b.is_active = true
  )
);

drop policy if exists "reactions_upsert" on public.post_reactions;
create policy "reactions_upsert" on public.post_reactions
for insert to authenticated
with check (
  auth.uid() = user_id
  and not exists (
    select 1
    from public.user_bans b
    where b.user_id = auth.uid() and b.is_active = true
  )
);

drop policy if exists "reactions_read_own" on public.post_reactions;
create policy "reactions_read_own" on public.post_reactions
for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "reactions_update_own" on public.post_reactions;
create policy "reactions_update_own" on public.post_reactions
for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "reactions_delete_own" on public.post_reactions;
create policy "reactions_delete_own" on public.post_reactions
for delete to authenticated
using (auth.uid() = user_id);

drop policy if exists "reports_insert" on public.reports;
create policy "reports_insert" on public.reports
for insert to authenticated
with check (
  auth.uid() = reporter_user_id
  and not exists (
    select 1
    from public.user_bans b
    where b.user_id = auth.uid() and b.is_active = true
  )
);

-- 封禁表：用户仅可读取自己的封禁状态（用于前端提示可选）
drop policy if exists "user_bans_read_own" on public.user_bans;
create policy "user_bans_read_own" on public.user_bans
for select to authenticated
using (user_id = auth.uid() and is_active = true);
